### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/syngrafias#36]
In the spirit of getting more contributors to the project, the above documents would be appreciated.

**Comment by a-developer-and-her-mac** [comment]
For the CODE_OF_CONDUCT.md, would using the github template option be ok? If so, I might be willing to take this on.

**Comment by t0xic0der** [comment]
Hi @a-developer-and-her-mac, that would work just fine. I'm assigning this issue to you. Be sure to register to our official Hacktoberfest event as that is how we'd be able coordinate the tasks by following this link http://organize.mlh.io/participants/events/4659-hack-astrosonic. 

Also, feel free to leave a star if you found the project worthy of it. Happy hacking! 😄

**Comment by a-developer-and-her-mac** [comment]
Hey @t0xic0der, by working on this issue am I required to attend the online meetup? Because I don't think I'll be able to make it.

**Comment by t0xic0der** [comment]
It's not necessary per se and that it's a timezone issue. I would still ask your registration as it would make sure that your email stays with us whenever the contributors need to contact you back.

**Comment by t0xic0der** [comment]
The issue was addressed with the latest merge. (#41)
