### ISSUE TITLE
While entering single character in the document title, It's logging twice in the activity log.

### ISSUE THREAD

**Issue by s0umadeep** [t0xic0der/syngrafias#40]
Steps you should perform to replicate the given scenario :
1. In Syngrafias "Welcome" tab, Enter your "User Name"
2. Generate "Workspace" key
3. After that document section will get opened.
4. Type '1' in the document title
5. Check the "Activities" log icon in the top right, as It's logging twice for single character.

Also find the attached image for the same.
![Screenshot from 2020-09-28 22-17-25](https://user-images.githubusercontent.com/70836563/94462894-cc2d8b80-01d9-11eb-826c-312e4f238364.png)

**Comment by t0xic0der** [comment]
Thank you for reporting the bug. We would look into it.

**Comment by cjoshi015** [comment]
Hey @t0xic0der , I would like to work upon it

**Comment by t0xic0der** [comment]
Cool, @cjoshi015. I am assigning you this issue.

**Comment by cjoshi015** [comment]
Hey @t0xic0der  ,Issue is resolved .I have created the pull request . please review it

**Comment by t0xic0der** [comment]
With the rewrite merge, this issue is not relevant anymore.
