### ISSUE TITLE
The menu bar at the top is supposed to be stuck there

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/syngrafias#56]
The menu bar at the top is supposed to be stuck there and should not be subjected to reposition or shifted out of the current viewport when scrolled away.

**Before scrolling**
![image](https://user-images.githubusercontent.com/49605954/99631634-ef4e1c00-2a61-11eb-8d66-dd978a9e757b.png)

**After scrolling**
![image](https://user-images.githubusercontent.com/49605954/99631480-ae560780-2a61-11eb-81e6-3d8f87c7882b.png)

**Comment by shivangswain** [comment]
I'd like to do this, please assign it to me.

**Comment by t0xic0der** [comment]
Closed via #64.
