### ISSUE TITLE
Add slider to modify partition width of cell 

### ISSUE THREAD

**Issue by VaibhavSaini19** [t0xic0der/syngrafias#59]
## 🚀 Feature

Add a slider in between the cell's code area and preview partition to enable the user to modify their width as desired

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

This would enhance the user experience greatly

**Comment by VaibhavSaini19** [comment]
@t0xic0der I would like to take this up

**Comment by t0xic0der** [comment]
Closed via #71.
