### ISSUE TITLE
Build documentation saving functionality for the remake

### ISSUE THREAD

**Issue by VaibhavSaini19** [t0xic0der/syngrafias#60]
## 🚀 Feature

Add buttons to allow the user to open / save a document 

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

Currently, there is no option to save document in the remake branch

**Comment by s-katte** [comment]
I would like to work on this issue.

**Comment by tripathyprateek** [comment]
@t0xic0der you need to assign @s-katte here 👀

**Comment by t0xic0der** [comment]
Whoops! My bad. I will assign it to him right away. :smile:

**Comment by t0xic0der** [comment]
Closed via #72
