### ISSUE TITLE
Build documentation opening functionality for the remake

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/syngrafias#62]
## 🚀 Feature

Add buttons to allow the user to open / save a document 

## Have you spent some time to check if this issue has been raised before?

Yes, similar issue doesn't exist

### Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md)?

Yes

## Pitch

Currently, there is no option to open document in the remake branch

**Comment by tripathyprateek** [comment]
Can I take this up?

**Comment by t0xic0der** [comment]
Closed via #78.
