### ISSUE TITLE
Make changes in the README.md for single process implementation

### ISSUE THREAD

**Issue by t0xic0der** [t0xic0der/syngrafias#67]
**Check Duplicate issue**
There ain't no issue like this.

**What needs to be changed**
The README.md should reflect new changes as per the single process execution.

**Comment by t0xic0der** [comment]
Take a look at this.

https://github.com/t0xic0der/syngrafias/wiki/Usage-2.0

CC @VaibhavSaini19 @tripathyprateek @shivangswain @s-katte

**Comment by tripathyprateek** [comment]
Looks good to me.

**Comment by t0xic0der** [comment]
https://github.com/t0xic0der/syngrafias/wiki/Usage-2.0 

is now 

https://github.com/t0xic0der/syngrafias/wiki/Usage

Closing this issue.
