### ISSUE TITLE
Textarea doesn't occupy parent's full height

### ISSUE THREAD

**Issue by VaibhavSaini19** [t0xic0der/syngrafias#79]
**Description**

The textarea in the `fomantic and asciidoc` branch does not occupy the full height of its parent container as its row size is given 2.

**Expected Behavior**

Textarea size increases automatically to fill parent container height

**Screenshot**<p>&nbsp;</p>

![Screenshot (187)](https://user-images.githubusercontent.com/32795689/101901495-1ddd9380-3bd7-11eb-8ef4-edc97b1c42f7.png)

**Enviroment:**
- Host OS: Windows 10
- Browser: Chrome Version 86.0.4240.198

**To Reproduce**
1. Open a Syngrafias document
2. Add a new cell, if doesn't exist
3. Type or paste some large text content in the input textarea

---
[Optional] **Additional Context**

This issue should be fixed only after #71 is merged

**Comment by VaibhavSaini19** [comment]
@t0xic0der I would like to work on this after the mentioned PR is merged

**Comment by t0xic0der** [comment]
I am assigning this issue to you.

**Comment by t0xic0der** [comment]
Closed #79 via #82
