### ISSUE TITLE
Add toast messages on various events.

### ISSUE THREAD

**Issue by s-katte** [t0xic0der/syngrafias#84]
**Check Duplicate issue**
Done

**Pitch your idea/new feature to add**
There are no toast messages on various events like editing documents, new user joined events, etc. like ```cellular``` version have.

## Note

PRs solving this issue must be made to [s-katte/syngrafias/tree/full-height-editor](https://github.com/s-katte/syngrafias/tree/full-height-editor) fork.

**Comment by s-katte** [comment]
I would like to pick this up

**Comment by t0xic0der** [comment]
Done
